---

name: Generate fish completion
on:
  # schedule:
  #   - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Chekcout source
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          version: '>= 363.0.0'

      - name: Generate bq
        run: bash .github/workflows/generate_bq.bash

      - name: Generate gcloud
        run: bash .github/workflows/generate_gcloud.bash

      - name: Generate gsutil
        run: bash .github/workflows/generate_gsutil.bash

      - name: Push to master
        run: |
          CHANGES=$(git status -s | grep -v .github | wc -l)
          echo "[INFO] CHANGES = $CHANGES"
          if [[ $CHANGES -gt 0 ]]; then
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add -A
            git commit -am "auto generate bq.fish $(date +'%Y-%m-%d')"
            git push
          fi
